### PR TITLE
Added cretion date to backend

### PR DESCRIPTION
**Pull request by dramicaninstefan**
Added cretion date to backend and updated migration

### CODE REVIEW

**Comment by ognjenkurtic** [comment]
Do we need a database migration for the CreationDate property on the Singatures model? @dramicaninstefan

**Comment by dramicaninstefan** [comment]
I would say yes, because we are adding a new property to the Signatures table in the database. Also, when we talked last time, you told me to create a new migration, or did I misunderstand?

**Comment by ognjenkurtic** [comment]
> I would say yes, because we are adding a new property to the Signatures table in the database. Also, when we talked last time, you told me to create a new migration, or did I misunderstand?

Yes, please add a migration in the same PR and then it is good to go.

**Comment by dramicaninstefan** [comment]
> > I would say yes, because we are adding a new property to the Signatures table in the database. Also, when we talked last time, you told me to create a new migration, or did I misunderstand?
> 
> Yes, please add a migration in the same PR and then it is good to go.

Just added migration to PR

**Pull request merged**
